sudo: required

dist: trusty

language: go

go:
  - 1.11.x

go_import_path: github.com/fission/fission

cache:
  directories:
    - $HOME/google-cloud-sdk/
    - $HOME/k8scli

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - sudo apt-get -y install apache2-utils
  - sudo sysctl net.ipv6.conf.all.disable_ipv6=0

install:
  - go get github.com/Masterminds/glide
  - hack/travis-kube-setup.sh

env:
  - KUBECONFIG=${HOME}/.kube/config PATH=$HOME/k8scli:${PATH}

before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - hack/verify-gofmt.sh
  - hack/verify-govet.sh
  - helm lint charts/fission-all/ charts/fission-core/
  - glide install -v
  - go build -o fission/fission fission/*.go
  - ./fission-bundle/build.sh
  - hack/runtests.sh

script:
  - cd ${TRAVIS_BUILD_DIR}
  - test/build_and_test.sh
  - test/upgrade/fission_upgrade_test.sh

